version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: dpms_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dpms_redis
    restart: always
    ports:
      - "6385:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/sharathim/s_board-backend:latest
    container_name: dpms_backend
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
    ports:
      - "5055:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      # Mount the firebase service account credentials dynamically at runtime
      - ./firebase-service-account.json:/app/firebase-service-account.json

  frontend:
    image: ghcr.io/sharathim/s_board-frontend:latest
    container_name: dpms_frontend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
